#!/bin/bash

echo "Please enter server eg. brix.fatbeehive.com"
read server

echo "Please enter local path eg. /server/www/yoursite/www"
read path

rm -fr $path
mkdir -p $path
chown -R g+w $path

echo "Creating path..."

echo "Please enter your remote username eg. rambo"
read user

hg clone ssh://$user@$server/$path $path

echo "cloning.."

echo "Please enter the database eg. lorem_site"
read database

echo "Please enter the database password eg. myspassword"
read mysql_pass

echo "Getting db"

ssh $user@$server "mysqldump -u $user -p$mysql_pass $database > ~/mysql/$database.sql"
scp -pr $user@$server:/home/$user/mysql/$database.sql ~/mysql_dump/$database.sql
mysql -u $user -p$mysql_pass --execute="drop database $database"
mysql -u $user -p$mysql_pass --execute="create database $database"
mysql -u $user -p$mysql_pass $database <  ~/mysql_dump/$database.sql

echo "Database created"

echo "Please enter the path to remote virtualhost files eg. /etc/httpd/conf/vhosts/site.conf"
read vhost_path

scp -pr $user@$server:$vhost_path $vhost_path
cat $vhost_path >> /etc/apache2/httpd.conf 
apachectl restart

echo "
TODO

change common.inc.php to have correct db details aka emile emile123

Get virtualhost

Get data dir if needed

echo '127.0.0.1	money4 > /etc/hosts'

"
