#! /bin/bash

if cmp ~/.vimrc /Users/emileswarts/.vimrc &> /dev/null
	then echo "Files a and b are identical"
	else echo "Files a and b are different"
fi

if grep -q vim ~/.vimrc
	then echo "File contains at least one occurence of bash"
	else echo "File does not contain bla"
fi

word=Linux
letter_sequence=inu
if echo "$word" | grep -q "$letter_sequence"
then 
	echo "$letter_sequence found"
else
	echo "$letter_sequence no found"
fi
