#! /bin/bash

#Escaped characters

#######################################################
#Firstly let's show some basic escaped character usage
######################################################

#escaping a newline

echo ""
echo "This will print
as two lines"

echo "This will print \
as one line"

echo;echo 
echo "=========="

echo "\v\v\v\v\v\v"
echo -e "\v\v\v\v\v\v"

echo 
echo "QUOTATION MARKS"
echo "=========="
echo -e "\043"
echo "=========="

echo; echo "NEWLINE and (myabe) BEEP"
echo $'\n'
echo $'\a'

echo "Introducing the \$\'...\' string expansion construct... "
echo "...featuring more quotation marks"

echo $'\t \042 \t' #Quote " framed by tabs

#It also works with hexadecimal values in an $'\xhhh' construct
echo $'\t \x22 \t'

#Assigning ascii chars to variables
quote=$'\042'
echo "$quote Quoted string $quote and this lies outside of the quotes"
echo 

#Concatenating  ASCII chars in a variable
triple_underline=$'\137\137\137'
echo "$triple_underline UNDERLINE $triple_underline"

echo 

ABC=$'\101\102\103\010'
echo $ABC

escape=$'\033'
echo "\"escape\" echos as $escape"

echo 
exit 0
