#! /bin/bash

true
echo "exit status of \"true\" = $?"

!true
echo "exit status of \"true\" = $?"

ls |bogus_command
echo "exit status of \"true\" = $?"

! ls |bogus_command
echo "exit status of \"true\" = $?"
